feat: new makefile

diff --git a/_extra/Makefile.hbs b/_extra/Makefile.hbs
--- a/_extra/Makefile.hbs
+++ b/_extra/Makefile.hbs
@@ -1,33 +1,49 @@
-PACKAGE_ID := {{id}}
+PACKAGE_ID := $(shell sed -n -r -e "s/\s*id\s*:\s*['\"](.+)['\"],/\1/ p" startos/manifest.ts)
+INGREDIENTS := $(shell start-cli s9pk list-ingredients)
 
-# Phony targets
-.PHONY: all clean install
+.PHONY: all clean install check-deps check-init check-ts
 
-# Default target
 all: ${PACKAGE_ID}.s9pk
+	@echo " Done!"
+	@echo " Filesize:$(shell du -h $(PACKAGE_ID).s9pk) is ready"
 
-# Build targets
-${PACKAGE_ID}.s9pk: $(shell start-cli s9pk list-ingredients)
+check-deps:
+	@if ! command -v start-cli > /dev/null; then \
+		echo "Error: start-cli not found. Please install it first."; \
+		exit 1; \
+	fi
+
+check-init:
+	@if [ ! -f ~/.startos/developer.key.pem ]; then \
+		start-cli init; \
+	fi
+
+check-ts:
+	@npm run check
+
+${PACKAGE_ID}.s9pk: assets $(INGREDIENTS) | check-deps check-init
 	start-cli s9pk pack
 
-javascript/index.js: $(shell find startos -name "*.ts") tsconfig.json node_modules package.json
+javascript/index.js: $(shell find startos -name "*.ts") tsconfig.json node_modules package.json check-ts
 	npm run build
+	$(eval INGREDIENTS := $(shell start-cli s9pk list-ingredients))
 
-node_modules: package.json package-lock.json
+assets:
+	mkdir -p assets
+
+node_modules: package-lock.json
 	npm ci
 
 package-lock.json: package.json
 	npm i
 
-# Clean target
 clean:
 	rm -rf ${PACKAGE_ID}.s9pk
 	rm -rf javascript
 	rm -rf node_modules
 
-# Install target
-install:
+install: | check-deps check-init
 	@if [ ! -f ~/.startos/config.yaml ]; then echo "You must define \"host: http://server-name.local\" in ~/.startos/config.yaml config file first."; exit 1; fi
-	@echo "\nInstalling to $$(grep -v '^#' ~/.startos/config.yaml | cut -d'/' -f3) ...\n"
-	@[ -f $(PACKAGE_ID).s9pk ] || ( $(MAKE) && echo "\nInstalling to $$(grep -v '^#' ~/.startos/config.yaml | cut -d'/' -f3) ...\n" )
+	@echo -e "\nInstalling to $$(grep -v '^#' ~/.startos/config.yaml | cut -d'/' -f3) ...\n"
+	@[ -f $(PACKAGE_ID).s9pk ] || ( $(MAKE) && echo -e "\nInstalling to $$(grep -v '^#' ~/.startos/config.yaml | cut -d'/' -f3) ...\n" )
 	@start-cli package install -s $(PACKAGE_ID).s9pk
